language: java
jdk:
- oraclejdk8
env:
  global:
  - DATABASE_URL=postgres://postgres:@localhost:5432/appointments
  - TWILIO_ACCOUNT_SID=ACXXXXXXXXXXXXXXXXX
  - TWILIO_AUTH_TOKEN=your_token
  - TWILIO_NUMBER=your_twilio_number
before_script:
- psql -c 'create database appointments;' -U postgres
- mvn exec:java -Dexec.mainClass="com.twilio.appointmentreminders.Migrator"
